### ISSUE TITLE
ODH 1.10 Release Tracker

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-community#104]
Links to tracker issues for components planning updates in this

- [x] ODH Operator
- [x] ODH Dashboard 
- [x] ODH Notebook Controller
- [x] ODH Workbench Images
- [x] Data Science Pipelines
- [x] Model Serving
- [x] AI Explainability
        - N/A
- [x] Distributed Workloads 
- [x] opendatahub.io
- [x] Release Notes
- [x] Component Blogs

**Comment by HumairAK** [comment]
ODH 1.10 release should include DSP 1.4: 

Change Logs:
* https://github.com/opendatahub-io/data-science-pipelines-operator/releases/tag/v1.4.0
* https://github.com/opendatahub-io/data-science-pipelines/releases/tag/v1.4.0

**Comment by andrewballantyne** [comment]
Dashboard releases:
- ODH Manifests: https://github.com/opendatahub-io/odh-manifests/pull/934
- Release Notes: https://github.com/opendatahub-io/odh-dashboard/releases/tag/v2.15.0-incubation

**Comment by anishasthana** [comment]
Distributed Workloads: https://github.com/opendatahub-io/distributed-workloads/releases/tag/v1.0.0-rc.1

**Comment by harshad16** [comment]
Workbenches (IDE):

No new change from ODH v1.9 

Notebook-images: https://github.com/opendatahub-io/notebooks/releases/tag/v1.10.0
Notebook-controller: https://github.com/opendatahub-io/kubeflow/releases/tag/v1.7.0-2

**Comment by heyselbi** [comment]
**Model Serving:**
KServe tag: https://github.com/opendatahub-io/kserve/releases/tag/v0.11.0
Modelmesh: is still part of odh-manifests. Planned transition is ODH 1.11. The PRs to be included will be posted in a separate comment here.

**Comment by VaishnaviHire** [comment]
Component Blogs:

- https://github.com/opendatahub-io/opendatahub.io/pull/196


Release Notes:
- https://github.com/opendatahub-io/opendatahub.io/pull/198

**Comment by zdtsw** [comment]
> Dashboard releases:
> 
> * ODH Manifests: [Dashboard v2.15-incubation odh-manifests#934](https://github.com/opendatahub-io/odh-manifests/pull/934)
> * Release Notes: https://github.com/opendatahub-io/odh-dashboard/releases/tag/v2.15.0-incubation

assume the one to use is the tip of branch "v2.15.0-incubation-fixes" ? found one more update on that branches after `v2.15.0-incubation` tag

**Comment by lucferbux** [comment]
`v2.15.0-incubation` contains https://github.com/opendatahub-io/odh-dashboard/commit/2dec5ecd8598a6ff33f0aa6b9f7a57da8ad3d5fc which was consider a blocker by QE downstream, that's in RHODS right now, I'll leave to Andrew confirm wether we wanna use that or the tag

**Comment by VaishnaviHire** [comment]
> `v2.15.0-incubation` contains [opendatahub-io/odh-dashboard@2dec5ec](https://github.com/opendatahub-io/odh-dashboard/commit/2dec5ecd8598a6ff33f0aa6b9f7a57da8ad3d5fc) which was consider a blocker by QE downstream, that's in RHODS right now, I'll leave to Andrew confirm wether we wanna use that or the tag

Sorry forgot to update this issue. I have already confirmed with andrew, the expected release branch is `v2.15.0-incubation-fixes`

cc: @lucferbux @zdtsw

**Comment by andrewballantyne** [comment]
I think I may need to do another release to catch the issue we fixed for QE. Because there will be no other way to deliver that in 1.10. @VaishnaviHire when is the release happening? Has it happened?

**Comment by andrewballantyne** [comment]
> I think I may need to do another release to catch the issue we fixed for QE. Because there will be no other way to deliver that in 1.10. @VaishnaviHire when is the release happening? Has it happened?

Talked with @VaishnaviHire on slack -- they are aiming to release today. We missed moving the fix over (we lack the automation to do a mid-day turn around on the image); this will need to be documented in our [release notes](https://github.com/opendatahub-io/odh-dashboard/releases/tag/v2.15.0-incubation). 

For posterity, it's not a "blocker" so much as it's a high critical bug. QE had automation relying on it so I fixed it and spawned a conversation about avoiding these scenarios in the future.
