### ISSUE TITLE
ODH 1.11 Release Tracker

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-community#118]
Links to tracker issues for components planning updates in this

- [ ] ODH Operator
- [x] ODH Dashboard 
- [x] ODH Notebook Controller
- [x] ODH Workbench Images
- [x] Data Science Pipelines
- [x] Model Serving
- [x] AI Explainability
- [x] Distributed Workloads 
- [x] opendatahub.io
- [ ] Release Notes
- [ ] Component Blogs

**Comment by andrewballantyne** [comment]
Dashboard will do a release tomorrow when our image builds tonight.

**Comment by VaishnaviHire** [comment]
cc: @harshad16 @Jooho @RobGeada @HumairAK @VedantMahabaleshwarkar @heyselbi

**Comment by andrewballantyne** [comment]
@VaishnaviHire Dashboard has released incubation. Tag `v2.17.0-incubation`, release notes: https://github.com/opendatahub-io/odh-dashboard/releases/tag/v2.17.0-incubation

**Comment by israel-hdez** [comment]
@VaishnaviHire @zdtsw We've created KServe's `v0.11.1.0`, which is what ODH 1.11 should point to.
We'll update you soon about the other repos.

**Comment by harshad16** [comment]
Workbench IDE: 

Notebooks
Tags: [v1.12.0](https://github.com/opendatahub-io/notebooks/blob/v1.12.0/manifests/overlays/additional/kustomization.yaml)
Release-Note: https://github.com/opendatahub-io/notebooks/releases/tag/v1.12.0

Notebook-controller:
Tags: [v1.7.0-5](https://github.com/opendatahub-io/kubeflow/tree/v1.7.0-5/components/base)
Release-Note: https://github.com/opendatahub-io/kubeflow/releases/tag/v1.7.0-5

Please point the operator to these version for the workbenches.

**Comment by heyselbi** [comment]
**Modelmesh**
branch: https://github.com/opendatahub-io/modelmesh-serving/tree/release-0.11.1
tag: [v0.11.1.0](https://github.com/opendatahub-io/modelmesh-serving/releases/tag/v0.11.1.0)
release: https://github.com/opendatahub-io/modelmesh-serving/releases/tag/v0.11.1.0

**odh-model-controller**
branch: https://github.com/opendatahub-io/odh-model-controller/tree/release-0.11.1
tag: [v0.11.1.0](https://github.com/opendatahub-io/odh-model-controller/releases/tag/v0.11.1.0)
release: https://github.com/opendatahub-io/odh-model-controller/releases/tag/v0.11.1.0

**kserve**
branch: https://github.com/opendatahub-io/kserve/tree/release-v0.11.1
tag: [v0.11.1.0](https://github.com/opendatahub-io/kserve/releases/tag/v0.11.1.0)
release: https://github.com/opendatahub-io/kserve/releases/tag/v0.11.1.0

**Comment by VaishnaviHire** [comment]
Hi @dimakis @RobGeada !! What are the release tags for DW and Trusty AI for the ODH release?

**Comment by anishasthana** [comment]
Hi @VaishnaviHire , we will be publishing a new release this week.
The tag should be something similar to `v1.0.0`.

**Comment by VaishnaviHire** [comment]
> Hi @VaishnaviHire , we will be publishing a new release this week. The tag should be something similar to `v1.0.0`.

New release can be added to next release on Thursday. Do we continue with the old tag for this one?

**Comment by anishasthana** [comment]
>New release can be added to next release on Thursday. Do we continue with the old tag for this one?
Let's do that

**Comment by zdtsw** [comment]
> **Modelmesh** branch: https://github.com/opendatahub-io/modelmesh-serving/tree/release-0.11.1 tag: [v0.11.1.0](https://github.com/opendatahub-io/modelmesh-serving/tree/v0.11.1.0) release: https://github.com/opendatahub-io/modelmesh-serving/releases/tag/v0.11.1.0
> 
> **odh-model-controller** branch: https://github.com/opendatahub-io/odh-model-controller/tree/release-0.11.1 tag: [v0.11.1.0](https://github.com/opendatahub-io/odh-model-controller/tree/v0.11.1.0) release: https://github.com/opendatahub-io/odh-model-controller/releases/tag/v0.11.1.0
> 
> **kserve** branch: https://github.com/opendatahub-io/kserve/tree/release-v0.11.1 tag: [v0.11.1.0](https://github.com/opendatahub-io/kserve/tree/v0.11.1.0) release: https://github.com/opendatahub-io/kserve/releases/tag/v0.11.1.0

for ODH, do we still need `modelmesh-monitoring`? i just realize, once we get rid of "odh-manifests" of ODH, then this is not gonna work https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/components/modelmeshserving/modelmeshserving.go#L21 unless we keep getting these manifests from ODH odh-manifests

**Comment by zdtsw** [comment]
> > **Modelmesh** branch: https://github.com/opendatahub-io/modelmesh-serving/tree/release-0.11.1 tag: [v0.11.1.0](https://github.com/opendatahub-io/modelmesh-serving/tree/v0.11.1.0) release: https://github.com/opendatahub-io/modelmesh-serving/releases/tag/v0.11.1.0
> > **odh-model-controller** branch: https://github.com/opendatahub-io/odh-model-controller/tree/release-0.11.1 tag: [v0.11.1.0](https://github.com/opendatahub-io/odh-model-controller/tree/v0.11.1.0) release: https://github.com/opendatahub-io/odh-model-controller/releases/tag/v0.11.1.0
> > **kserve** branch: https://github.com/opendatahub-io/kserve/tree/release-v0.11.1 tag: [v0.11.1.0](https://github.com/opendatahub-io/kserve/tree/v0.11.1.0) release: https://github.com/opendatahub-io/kserve/releases/tag/v0.11.1.0
> 
> for ODH, do we still need `modelmesh-monitoring`? i just realize, once we get rid of "odh-manifests" of ODH, then this is not gonna work https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/components/modelmeshserving/modelmeshserving.go#L21 unless we keep getting these manifests from ODH odh-manifests

offline discussed, we dont need modelmesh-monitoring for ODH

**Comment by ruivieira** [comment]
TrustyAI 
- branch: https://github.com/trustyai-explainability/trustyai-service-operator/tree/release/1.11.1
- tag: https://github.com/trustyai-explainability/trustyai-service-operator/releases/tag/v1.11.1

**Comment by VaishnaviHire** [comment]
> **Modelmesh** branch: https://github.com/opendatahub-io/modelmesh-serving/tree/release-0.11.1 tag: [v0.11.1.0](https://github.com/opendatahub-io/modelmesh-serving/tree/v0.11.1.0) release: https://github.com/opendatahub-io/modelmesh-serving/releases/tag/v0.11.1.0
> 
> **odh-model-controller** branch: https://github.com/opendatahub-io/odh-model-controller/tree/release-0.11.1 tag: [v0.11.1.0](https://github.com/opendatahub-io/odh-model-controller/tree/v0.11.1.0) release: https://github.com/opendatahub-io/odh-model-controller/releases/tag/v0.11.1.0
> 
> **kserve** branch: https://github.com/opendatahub-io/kserve/tree/release-v0.11.1 tag: [v0.11.1.0](https://github.com/opendatahub-io/kserve/tree/v0.11.1.0) release: https://github.com/opendatahub-io/kserve/releases/tag/v0.11.1.0

Hi, during testing, we are seeing following errors for modelmesh controller: https://github.com/opendatahub-io/modelmesh-serving/blob/v0.11.1.0/config/overlays/odh/params.env#L4

```
Back-off pulling image "quay.io/opendatahub/modelmesh-controller:v0.11.1"
Failed to pull image "quay.io/opendatahub/modelmesh-controller:v0.11.1": rpc error: code = Unknown desc = reading manifest v0.11.1 in quay.io/opendatahub/modelmesh-controller: manifest unknown: manifest unknown
```

**Comment by andrewballantyne** [comment]
@VaishnaviHire I think we can close this one 🙂
