### ISSUE TITLE
ODH 1.10.1 Release Tracker

### ISSUE THREAD

**Issue by zdtsw** [opendatahub-io/opendatahub-community#122]
Links to tracker issues for components planning updates in this

- [x]  ODH Operator: N/A
- [x]  ODH Dashboard: N/A
- [x]  ODH Notebook Controller: N/A 
- [x]  ODH Workbench Images
- [x]  Data Science Pipelines : N/A
- [x]  Model Serving: N/A
- [x]  AI Explainability : N/A
- [x]  Distributed Workloads: N/A
- [ ]  opendatahub.io
- [ ]  Release Notes
- [ ]  Component Blogs

**Comment by harshad16** [comment]
Thank you for creating this release tracker.

Fixed Workbench manifests: https://github.com/opendatahub-io/notebooks/tree/v1.10.1


Release Notes:
```
Fixed Breaking Change
With v1.10 ODH, the PyTorch image was referencing an incorrect image sha, 
the detail of the issue can be found https://github.com/opendatahub-io/notebooks/issues/246.
This is fixed in this patch to point to the right reference.
```

**Comment by VaishnaviHire** [comment]
OperatorHub Release PR - https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3413
