### ISSUE TITLE
ODH 2.4 Release Tracker

### ISSUE THREAD

**Issue by zdtsw** [opendatahub-io/opendatahub-community#138]
Links to tracker issues for components planning updates in this

- [ ]  ODH Operator 
- [x]  ODH Dashboard: v2.17.0-incubation
- [x]  Workbench
  - [ ]  ODH Notebook Controller: v1.7.0-5
  - [ ]  ODH Workbench Images: v1.12.0
- [x]  Data Science Pipelines v1.6.0
- [x]  Model Serving
   - [x] Modelmesh v0.11.1.0
   - [ ] Kserve v0.11.1.0
- [x]  AI Explainability: 1.11.1
- [ ]  Distributed Workloads
  - [ ] Codeflare
  - [ ] Kuberay 
- [ ]  opendatahub.io
  - [ ]  Release Notes
  - [ ]  Component Blogs

**Comment by israel-hdez** [comment]
This is done, right?

**Comment by zdtsw** [comment]
> This is done, right?

yes, close it now
