### ISSUE TITLE
ODH 2.15 Release Tracker

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-community#154]
Links to tracker issues for components planning updates in this.  Please update you manifests before **July 12th**. 

Release Date: **July 15th**

### Comment Template for automation
```
#Release#
- component_name|release-branch|release-notes
```

**List of component_name:**

- [ ] modelregistry
- [ ] notebook-controller
- [ ] notebook
- [ ] codeflare
- [ ] ray
- [ ] kueue
- [ ] trainingoperator
- [ ] trustyai
- [ ] odh-dashboard
- [ ] data-science-pipelines-operator
- [ ] model-mesh
- [ ] kserve
- [ ] model-mesh-serving
- [ ] odh-model-controller

**Comment by AjayJagan** [comment]
Please note that
 - no space should be added before and after the `|`
 - Please add the correct `release-branch` and `release-notes` URL

**Comment by sutaakar** [comment]
#Release#
 - codeflare|release-branch-url|release-notes-url
 - component_name2|release-branch-url|release-notes-url
 - component_name3|release-branch-url|release-notes-url

    codeflare|https://github.com/opendatahub-io/codeflare-operator/tree/v1.5.0-odh | https://github.com/opendatahub-io/codeflare-operator/releases/tag/v1.5.0-odh
    ray|https://github.com/opendatahub-io/kuberay/tree/v1.1.2-odh | https://github.com/opendatahub-io/kuberay/releases/tag/v1.1.2-odh
    kueue|https://github.com/opendatahub-io/kueue/tree/v0.7.0-odh-test | https://github.com/opendatahub-io/kueue/releases/tag/v0.7.0-odh-test
    trainingoperator|https://github.com/opendatahub-io/training-operator/tree/v1.8.0-odh | https://github.com/opendatahub-io/training-operator/releases/tag/v1.8.0-odh

**Comment by andrewballantyne** [comment]
#Release#
- odh-dashboard | https://github.com/opendatahub-io/odh-dashboard/tree/v2.24.2-odh-release | https://github.com/opendatahub-io/odh-dashboard/releases/tag/v2.24.2-odh

**Comment by ruivieira** [comment]
#Release#
- trustyai | https://github.com/trustyai-explainability/trustyai-service-operator/tree/release/1.23.0 | https://github.com/trustyai-explainability/trustyai-service-operator/releases/tag/v1.23.0

**Comment by israel-hdez** [comment]
Adding model mesh twice, because I see it twice in the list up.

#Release#
- model-mesh| https://github.com/opendatahub-io/modelmesh-serving/tree/v0.12.0.2-rc0 | https://github.com/opendatahub-io/modelmesh-serving/releases/tag/v0.12.0.2-rc0
- kserve | https://github.com/opendatahub-io/kserve/tree/v0.12.1.3 | https://github.com/opendatahub-io/kserve/releases/tag/v0.12.1.3
- odh-model-controller | https://github.com/opendatahub-io/odh-model-controller/tree/v0.12.0.3 | https://github.com/opendatahub-io/odh-model-controller/releases/tag/v0.12.0.3
- model-mesh-serving | https://github.com/opendatahub-io/modelmesh-serving/tree/v0.12.0.2-rc0 | https://github.com/opendatahub-io/modelmesh-serving/releases/tag/v0.12.0.2-rc0

**Comment by tarilabs** [comment]
@AjayJagan @VaishnaviHire thank you for this automation!
In the case of Model Registry component:
- `release-branch-url` is clear, will use the Operator release branch
- but what about the _release notes_, please?
in the case of Model Registry the release notes of interests are actually 3:
  - upstream Kubeflow (this is where main features are developed, [example](https://github.com/kubeflow/model-registry/releases/tag/v0.2.3-alpha)),
  - midstream Model Registry (this is where any significant ODH-related feature is mentioned, [example](https://github.com/opendatahub-io/model-registry/releases/tag/v0.2.3))
  - and the MR Operator itself (this is where operator capabilities are mentioned, [example](https://github.com/opendatahub-io/model-registry-operator/releases/tag/v0.2.3))

which one should I link for `release-notes` or can that be multiple links, please?

#Release#
- modelregistry | https://github.com/opendatahub-io/model-registry-operator/tree/release/v0.2.3 | https://github.com/opendatahub-io/model-registry-operator/releases/tag/v0.2.3

**Comment by AjayJagan** [comment]
@tarilabs , the one you have added is correct. It should point to the MR operator. Thanks 👍

**Comment by harshad16** [comment]
#Release#

- notebooks|[https://github.com/opendatahub-io/notebooks/blob/v1.20.0|https://github.com/opendatahub-io/notebooks/releases/tag/v1.20.0](https://github.com/opendatahub-io/notebooks/blob/v1.20.0%7Chttps://github.com/opendatahub-io/notebooks/releases/tag/v1.20.0)
- notebook-controller|[https://github.com/opendatahub-io/kubeflow/tree/v1.7.0-13|https://github.com/opendatahub-io/kubeflow/releases/tag/v1.7.0-13](https://github.com/opendatahub-io/kubeflow/tree/v1.7.0-13%7Chttps://github.com/opendatahub-io/kubeflow/releases/tag/v1.7.0-13)

**Comment by AjayJagan** [comment]
#Release#
-  data-science-pipelines-operator | https://github.com/opendatahub-io/data-science-pipelines-operator/tree/v2.3.0 | https://github.com/opendatahub-io/data-science-pipelines-operator/releases/tag/v2.3.0

**Comment by VaishnaviHire** [comment]
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4807
