### ISSUE TITLE
ODH 2.16 Release Tracker

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-community#155]
Links to tracker issues for components planning updates in this.  Please update you manifests before **August 2nd**. 

Release Date: **August 5th**

### Comment Template for automation
```
#Release#
- component_name|release-branch|release-notes
```

**List of component_name:**

- [ ] modelregistry
- [ ] notebook-controller
- [ ] notebooks
- [ ] codeflare
- [ ] ray
- [ ] kueue
- [ ] trainingoperator
- [ ] trustyai
- [ ] odh-dashboard
- [ ] data-science-pipelines-operator
- [ ] model-mesh
- [ ] kserve
- [ ] model-mesh-serving
- [ ] odh-model-controller

**Comment by AjayJagan** [comment]
Please note that
 - Please add the `#Release#` for the automation to read the entries.
 - A space can be added before or after the delimiter '|' which prevents github from making the URL malformed.
 - Please add the correct `release-branch` and `release-notes` URL
 - Multiple component releases of the same team can use the `-` to add multiple entries
   eg: 
   ```
       #Release#
        - component_name1|release-branch-url|release-notes-url
        - component_name2|release-branch-url|release-notes-url
        - component_name3|release-branch-url|release-notes-url

**Comment by HumairAK** [comment]
#Release#

data-science-pipelines-operator|https://github.com/opendatahub-io/data-science-pipelines-operator/tree/v2.4.x|https://github.com/opendatahub-io/data-science-pipelines-operator/releases/tag/v2.4.0

**Comment by zdtsw** [comment]
FYI @dhirajsb

**Comment by andrewballantyne** [comment]
#Release#

odh-dashboard | https://github.com/opendatahub-io/odh-dashboard/tree/v2.25.1-odh-release | https://github.com/opendatahub-io/odh-dashboard/releases/tag/v2.25.1-odh

**Comment by harshad16** [comment]
#Release#

- notebooks| [https://github.com/opendatahub-io/notebooks/tree/v1.21.0](https://github.com/opendatahub-io/notebooks/tree/v1.21.0) | [https://github.com/opendatahub-io/notebooks/releases/tag/v1.21.0](https://github.com/opendatahub-io/notebooks/releases/tag/v1.21.0)
- notebook-controller| [https://github.com/opendatahub-io/kubeflow/tree/v1.7.0-14](https://github.com/opendatahub-io/kubeflow/tree/v1.7.0-14) | [https://github.com/opendatahub-io/kubeflow/releases/tag/v1.7.0-14](https://github.com/opendatahub-io/kubeflow/releases/tag/v1.7.0-14)

**Comment by ruivieira** [comment]
#Release#
     - trustyai | https://github.com/trustyai-explainability/trustyai-service-operator/tree/release/1.24.0 | https://github.com/trustyai-explainability/trustyai-service-operator/releases/tag/v1.24.0

**Comment by tarilabs** [comment]
#Release#

modelregistry | https://github.com/opendatahub-io/model-registry-operator/tree/release/v0.2.4 | https://github.com/opendatahub-io/model-registry-operator/releases/tag/v0.2.4

**Comment by zdtsw** [comment]
@israel-hdez / @Jooho FYI

**Comment by AjayJagan** [comment]
#Release#

- codeflare | https://github.com/opendatahub-io/codeflare-operator/tree/v1.5.0-odh | https://github.com/opendatahub-io/codeflare-operator/releases/tag/v1.5.0-odh
- ray | https://github.com/opendatahub-io/kuberay/tree/v1.1.2-odh | https://github.com/opendatahub-io/kuberay/releases/tag/v1.1.2-odh
- kueue | https://github.com/opendatahub-io/kueue/tree/v0.7.0-odh-test | https://github.com/opendatahub-io/kueue/releases/tag/v0.7.0-odh-test
- trainingoperator | https://github.com/opendatahub-io/training-operator/tree/v1.8.0-odh | https://github.com/opendatahub-io/training-operator/releases/tag/v1.8.0-odh

**Comment by AjayJagan** [comment]
#Release#

- model-mesh | https://github.com/opendatahub-io/modelmesh-serving/tree/v0.12.0.2-rc0 | https://github.com/opendatahub-io/modelmesh-serving/releases/tag/v0.12.0.2-rc0
- kserve | https://github.com/opendatahub-io/kserve/tree/v0.12.1.3 | https://github.com/opendatahub-io/kserve/releases/tag/v0.12.1.3
- odh-model-controller | https://github.com/opendatahub-io/odh-model-controller/tree/v0.12.0.3 | https://github.com/opendatahub-io/odh-model-controller/releases/tag/v0.12.0.3

**Comment by israel-hdez** [comment]
Hopefully, this overrides the comment fromn @AjayJagan 

#Release#
- model-mesh| https://github.com/opendatahub-io/modelmesh-serving/tree/v0.12.0.3-rc0 | https://github.com/opendatahub-io/modelmesh-serving/releases/tag/v0.12.0.3-rc0
- kserve | https://github.com/opendatahub-io/kserve/tree/v0.12.1.4 | https://github.com/opendatahub-io/kserve/releases/tag/v0.12.1.4
- odh-model-controller | https://github.com/opendatahub-io/odh-model-controller/tree/v0.12.0.4 | https://github.com/opendatahub-io/odh-model-controller/releases/tag/v0.12.0.4

**Comment by andrewballantyne** [comment]
I believe this should be closed @AjayJagan @VaishnaviHire
