### ISSUE TITLE
ODH 2.20 Release Tracker

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-community#161]
Links to tracker issues for components planning updates in this.  Please update you manifests before . 

Release Date: **Oct 30th**

### Comment Template for automation
```
#Release#
- component_name|release-branch/release-tag|release-notes
```

**List of component_name:**

- [ ] modelregistry
- [ ] notebook-controller
- [ ] notebooks
- [ ] codeflare
- [ ] ray
- [ ] kueue
- [ ] trainingoperator
- [ ] trustyai
- [ ] odh-dashboard
- [ ] data-science-pipelines-operator
- [ ] model-mesh
- [ ] kserve
- [ ] model-mesh-serving
- [ ] odh-model-controller

**Comment by Ygnas** [comment]
#Release#

codeflare|https://github.com/opendatahub-io/codeflare-operator/tree/v1.10.0 | https://github.com/opendatahub-io/codeflare-operator/releases/tag/v1.10.0
ray|https://github.com/opendatahub-io/kuberay/tree/v1.1.0-odh-1 | https://github.com/opendatahub-io/kuberay/releases/tag/v1.1.0-odh-1
kueue|https://github.com/opendatahub-io/kueue/tree/v0.8.1-2 | https://github.com/opendatahub-io/kueue/releases/tag/v0.8.1-2
trainingoperator|https://github.com/opendatahub-io/training-operator/tree/v1.8.0-odh-3 | https://github.com/opendatahub-io/training-operator/releases/tag/v1.8.0-odh-3

**Comment by HumairAK** [comment]
#Release#

data-science-pipelines-operator|https://github.com/opendatahub-io/data-science-pipelines-operator/tree/v2.7.0 | https://github.com/opendatahub-io/data-science-pipelines-operator/releases/tag/v2.7.0

**Comment by harshad16** [comment]
#Release#

- notebooks| https://github.com/opendatahub-io/notebooks/tree/v1.24.0 | https://github.com/opendatahub-io/notebooks/releases/tag/v1.24.0
- notebook-controller| https://github.com/opendatahub-io/kubeflow/tree/v1.9.0-2 | https://github.com/opendatahub-io/kubeflow/releases/tag/v1.9.0-2

**Comment by HumairAK** [comment]
note that I just updated the DSPO tag from 2.7 -> 2.8 (dsp v1 removal changes)

**Comment by manaswinidas** [comment]
#Release#

odh-dashboard | https://github.com/opendatahub-io/odh-dashboard/tree/v2.28.1-odh-release | https://github.com/opendatahub-io/odh-dashboard/releases/tag/v2.28.1-odh

**Comment by hdefazio** [comment]
#Release#

- modelmesh | https://github.com/opendatahub-io/modelmesh/tree/release-0.12.0-rc0 | https://github.com/opendatahub-io/modelmesh/releases/tag/odh-v2.20

- model-mesh-serving | https://github.com/opendatahub-io/modelmesh-serving/tree/release-0.12.0-rc0 | https://github.com/opendatahub-io/modelmesh-serving/releases/tag/odh-v2.20

- kserve | https://github.com/opendatahub-io/kserve/tree/release-v0.12.1 | https://github.com/opendatahub-io/kserve/releases/tag/odh-v2.20

- odh-model-controller | https://github.com/opendatahub-io/odh-model-controller/tree/release-0.12.0 | https://github.com/opendatahub-io/odh-model-controller/releases/tag/odh-v2.20

**Comment by ruivieira** [comment]
#Release#
- trustyai | https://github.com/trustyai-explainability/trustyai-service-operator/tree/release/1.28.0 | https://github.com/trustyai-explainability/trustyai-service-operator/releases/tag/v1.28.0

**Comment by ruivieira** [comment]
@VaishnaviHire @zdtsw apologies for the late submission.

**Comment by VaishnaviHire** [comment]
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/5441
