### ISSUE TITLE
ODH 2.22.0 Tracker

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-community#163]
Links to tracker issues for components planning updates in this.  Please update you manifests before Dec 6th

Release Date: **Dec 9th**

### Comment Template for automation
```
#Release#
- component_name|release-branch/release-tag|release-notes
```

**List of component_name:**

- [x] modelregistry
- [x] notebook-controller
- [x] notebooks
- [x] codeflare
- [x] ray
- [x] kueue
- [ ] trainingoperator
- [x] trustyai
- [x] odh-dashboard
- [ ] data-science-pipelines-operator
- [x] model-mesh
- [x] kserve
- [x] model-mesh-serving
- [x] odh-model-controller

**Comment by atheo89** [comment]
#Release#

notebooks| https://github.com/opendatahub-io/notebooks/tree/v1.27.0 | https://github.com/opendatahub-io/notebooks/releases/tag/v1.27.0
notebook-controller| https://github.com/opendatahub-io/kubeflow/tree/v1.9.0-5 | https://github.com/opendatahub-io/kubeflow/releases/tag/v1.9.0-5

**Comment by ppadti** [comment]
#Release#

odh-dashboard | https://github.com/opendatahub-io/odh-dashboard/tree/v2.29.2-odh-release | https://github.com/opendatahub-io/odh-dashboard/releases/tag/v2.29.2-odh

**Comment by mholder6** [comment]
#Release#

-     odh-model-controller|https://github.com/opendatahub-io/odh-model-controller/tree/odh-v2.22|https://github.com/opendatahub-io/odh-model-controller/releases/tag/odh-v2.22
-     model-mesh-serving|https://github.com/opendatahub-io/modelmesh-serving/tree/odh-v2.22|https://github.com/opendatahub-io/modelmesh-serving/releases/tag/odh-v2.22
-     model-mesh|https://github.com/opendatahub-io/modelmesh-serving/tree/odh-v2.22|https://github.com/opendatahub-io/modelmesh-serving/releases/tag/odh-v2.22
-     kserve|https://github.com/opendatahub-io/kserve/tree/odh-v2.22|https://github.com/opendatahub-io/kserve/releases/tag/odh-v2.22
-

**Comment by tarilabs** [comment]
#Release#

modelregistry | https://github.com/opendatahub-io/model-registry-operator/tree/release/v0.2.11 | https://github.com/opendatahub-io/model-registry-operator/releases/tag/v0.2.11

**Comment by ruivieira** [comment]
#Release#
- trustyai| https://github.com/trustyai-explainability/trustyai-service-operator/tree/release/1.30.0 | https://github.com/trustyai-explainability/trustyai-service-operator/releases/tag/v1.30.0

**Comment by VaishnaviHire** [comment]
#Release#

data-science-pipelines-operator|https://github.com/opendatahub-io/data-science-pipelines-operator/tree/v2.8.0 | https://github.com/opendatahub-io/data-science-pipelines-operator/releases/tag/v2.8.0
