### ISSUE TITLE
ODH 1.8 Release

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/opendatahub-community#74]
Links to tracker issues for components planning updates in this 
- [ ] ODH Operator
- [ ] ODH Dashboard
- [ ] ODH Notebook Controller
- [ ] ODH Workbench Images
- [ ] Data Science Pipelines
- [ ] Model Serving
- [ ] AI Explainability
- [ ] Distributed Workloads

**Comment by heyselbi** [comment]
@LaVLaS I understand these should be the release notes from 1.7.0 to 1.8 right? Also, is there a release cadence for ODH? Is it every month or so? We are in the process of setting up our releases too (MLServing).

**Comment by LaVLaS** [comment]
> I understand these should be the release notes from 1.7.0 to 1.8 right?
The ODH code freeze will be this week.  You'll just need to catalog the MLServing changes that occurred between those dates.  

> Also, is there a release cadence for ODH? 
The release cadence is at least one release a month.  As we develop faster the goal is to cut a release at any given time based on the stability of the opendatahub-operator and odh-manifests.  The focus should be on tagging stable releases of your respective components then updating ODH to include that tagged release
