### ISSUE TITLE
Support for running ODH on Power Arch architecture

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/opendatahub-community#79]
An external volunteer has offered to assist in supporting ODH deployment on IBM Power Architecture.  This tracker issue will list out all of the task related to this work.  The goal is to provide the default ODH capabilities when running on IBM Power Architecture

- [ ] Provide a list of dependencies, version, and git URL for ODH
- [ ] Provide the source files and image registry for rebuilds of the container images for Power Architecture
- [ ] Provide an update to odh-manifests to deploy ODH components with Power Arch customizations
- [ ] Provide documentation on opendatahub.io to outline the steps for customizing ODH for deployment for IBM Power Arch

Additional images will be added as the work proceeds

**Comment by afsanjar** [comment]
Thanks for opening the github tracker for Power.
